### ISSUE TITLE
CEST components

### ISSUE THREAD

**Issue by MinhVo89** [MPR-UKD/calf#2]
Dear Developers,

First of all, thanks for your great contribution to the MRI community. I would like to as a question regarding the CEST components I want to create more CEST component and add it to your software. What should I do?

Best regards,

Minh

**Comment by intervall-ludger** [comment]
Hey @MinhVo89,

Thanks for pointing this out, I will include this in the ReadMe as well. 

You can easily extend the CEST pulses and set other boundaries locally by downloading the Calf Zip. After extracting the files, you will find the cest.ini file where you can manually adjust the pools. Here's a brief explanation of how you can do this:

In the cest.ini file, you will see the following configuration:

```
6 - No. of Lorentzian components (max = 20)
-6.000000 ! 6.000000  - frequency range
0.400000 ! 0.500000 ! 1.000000 ! lower bound, amplitude, upper bound of #1 = H2O
-1.500000 ! 0.000000 ! 1.500000 ! lower bound, frequeny, upper bound of #1 = H2O
0.200000 ! 2.000000 ! 5.000000 ! lower bound, width, upper bound of #1 = H2O
...
```

To add more CEST components, you can simply adjust the number of Lorentzian components and define the parameters for the new components. For example, if you want to add a 7th component, first change the number of components:

`7 - No. of Lorentzian components (max = 23)`

Then, add the parameters for the new component below the existing ones:

```
0.000000 ! 0.050000 ! 0.150000 ! lower bound, amplitude, upper bound of #7 = NewComponent
-2.600000 ! -1.600000 ! -0.600000 ! lower bound, frequeny, upper bound of #7 = NewComponent
0.200000 ! 2.000000 ! 5.000000 ! lower bound, width, upper bound of #7 = NewComponent
```

After making these changes, save the cest.ini file and the software should now include your new CEST component. You can also delete pools in the same way.

Best regards,
Ludger

**Comment by intervall-ludger** [comment]
@MinhVo89 did everything work for you?

**Comment by MinhVo89** [comment]
Dear Ludgerradke,

Thank you so much for your answers! It's helpful! 

Best regards,

Minh Vo

**Comment by MinhVo89** [comment]
Dear Ludgerradke,

I would like to ask a question:
1. Is it possible to change the line curve colour? For instance: I would like to change the colour of NOE to yellow.
2. How can you calculate the lb ampl, amplitude, ub ampl, lb freq... of the component from raw data?

Thanks and best regards,

Minh Vo

**Comment by intervall-ludger** [comment]
Dear @MinhVo89, 

1. To the best of my knowledge, the colors of the line curves depend on the order of the components and cannot typically be changed directly by the user. However, I will look into this matter further tomorrow and provide you with a more precise answer if there is a way to modify the colors.

2. To your question about the lower (lb) and upper (ub) limits for amplitude, frequency and other parameters: These values are not determined automatically, but must be specified by the user. They are best guided by the literature to determine appropriate limits for your research.

Best regards,
Ludger Radke
